apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: {{ template "fullname" . }}
  labels:
    microclimate-release: {{ .Values.microclimate.release.name }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http  
    port: {{ .Values.service.servicePort }}
  selector:
    app: "{{  .Chart.Name }}-selector"
